# Generated by Django 4.2.5 on 2023-12-11 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=40)),
                ("Email", models.EmailField(max_length=60)),
                ("Mobile", models.CharField(max_length=15)),
                ("Message", models.TextField()),
            ],
        ),
    ]
