# Generated by Django 4.2.5 on 2023-12-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="myproduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dprice", models.FloatField()),
                ("psize", models.CharField(max_length=20)),
                ("pprice", models.CharField(max_length=60)),
                ("ppic", models.ImageField(default="", upload_to="static/product/")),
                ("pdate", models.DateField()),
                (
                    "pcategory",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shop.category",
                    ),
                ),
            ],
        ),
    ]
