# Generated by Django 4.2.5 on 2023-12-12 10:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_myproduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="myproduct",
        ),
    ]
