# Generated by Django 4.2.5 on 2023-12-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0006_maincate_myproduct_mcategory"),
    ]

    operations = [
        migrations.CreateModel(
            name="mcart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("useid", models.CharField(max_length=70)),
                ("pid", models.IntegerField()),
                ("cdate", models.DateField()),
                ("status", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="morder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userid", models.CharField(max_length=70)),
                ("pid", models.IntegerField()),
                ("remarks", models.CharField(max_length=20)),
                ("odate", models.DateField()),
                ("status", models.BooleanField()),
            ],
        ),
    ]
