# Generated by Django 4.2.5 on 2023-12-13 03:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0007_mcart_morder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mcart",
            old_name="useid",
            new_name="userid",
        ),
    ]
