# Generated by Django 4.2.5 on 2023-12-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0008_rename_useid_mcart_userid"),
    ]

    operations = [
        migrations.CreateModel(
            name="register",
            fields=[
                ("name", models.CharField(max_length=50)),
                (
                    "email",
                    models.EmailField(max_length=70, primary_key=True, serialize=False),
                ),
                ("mobile", models.CharField(max_length=15)),
                ("ppic", models.ImageField(default="", upload_to="static/profile/")),
                ("passwd", models.CharField(max_length=60)),
                ("address", models.TextField()),
            ],
        ),
    ]
