# Generated by Django 4.2.5 on 2023-12-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0009_register"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcart",
            name="cdate",
            field=models.CharField(max_length=100),
        ),
    ]
