# Generated by Django 4.2.5 on 2023-12-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0014_alter_mcart_cdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcart",
            name="cdate",
            field=models.DateField(),
        ),
    ]
